
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marina ahmad
 */
public class displayacc extends javax.swing.JFrame {

    /**
     * Creates new form displayacc
     * @throws java.io.IOException
     */
    public displayacc() throws IOException {
        initComponents();
        readrecord();
    }
    public void readrecord() throws FileNotFoundException, IOException
    {      viewAcc[] v=new viewAcc[20];
           String out="";
    // Open the file
        FileReader fr=new FileReader("UserRecords.txt");
        try (BufferedReader in = new BufferedReader(fr)) {
            
            int i=1;
            boolean found=true;
            // Read records from the file
            for(int h=0;h<20;h++)
            {
                String data;
                while((data = in.readLine()) != null)
                {
                    StringTokenizer st=new StringTokenizer(data,",");
                    String passw=st.nextToken();
                    String name=st.nextToken();
                    
                    int age=Integer.parseInt(st.nextToken());
                    String l1=st.nextToken();
                    int L1=Integer.parseInt(l1);
                    String l2=st.nextToken();
                    int L2=Integer.parseInt(l2);
                    String l3=st.nextToken();
                    int L3=Integer.parseInt(l3);
                    
                    out=("Password: " + passw + "\nName: " + name + "\nAge: " + age);
                     DisplayBox.setText( out );
                    hide();
                   // v[h]=new viewAcc(passw,name,age,L1,L2,L3);
                }
                 //if(passw.equals(v[h].getId()))
                //{
                    //out=(v[h].view());
                    //DisplayBox.setText(out);
                    //break;
               // }
                //else
               // {
                     //DisplayBox.setText("INVALID ID...");
              //  }
            }
            //for(int g=0;g<20;g++)
            //{
               
            //}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DisplayBox = new javax.swing.JTextField();
        jbtnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("DISPLAY ACCOUNT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 11, 371, -1));

        DisplayBox.setBackground(new java.awt.Color(204, 255, 255));
        DisplayBox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DisplayBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DisplayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBoxActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 67, 837, 130));

        jbtnback.setBackground(new java.awt.Color(153, 255, 255));
        jbtnback.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnback.setForeground(new java.awt.Color(0, 153, 153));
        jbtnback.setText("BACK");
        jbtnback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/galaxy-hipster-wallpaper-hd-wallpapers-background-photos-tablet-artworks-4k-wallpaper-for-iphone-free-download-1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayBoxActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
  choose rint = new choose();
  rint.setVisible(true);
  hide();
    }//GEN-LAST:event_jbtnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displayacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displayacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displayacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displayacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new displayacc().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(displayacc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DisplayBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnback;
    // End of variables declaration//GEN-END:variables

    //private void initComponents() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
