
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marina ahmad
 */
public class level11 extends javax.swing.JFrame {

    /**
     * Creates new form level11
     */
    public level11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtl1q2 = new javax.swing.JTextField();
        jbtntryl1q2 = new javax.swing.JButton();
        jbtnmod1 = new javax.swing.JButton();
        jbtnl1q2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rumah.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 238));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Soalan 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Gambar di atas menunjukkan sebuah apa? Ejakan r_m_h ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 51, 489, 54));

        jtxtl1q2.setBackground(new java.awt.Color(204, 204, 255));
        jtxtl1q2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jtxtl1q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtl1q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtl1q2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtl1q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 295, 48));

        jbtntryl1q2.setBackground(new java.awt.Color(204, 204, 255));
        jbtntryl1q2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtntryl1q2.setText("TRY AGAIN");
        jbtntryl1q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtntryl1q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntryl1q2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtntryl1q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, 50));

        jbtnmod1.setBackground(new java.awt.Color(204, 204, 255));
        jbtnmod1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnmod1.setText("END");
        jbtnmod1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnmod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmod1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 140, 50));

        jbtnl1q2.setBackground(new java.awt.Color(204, 204, 255));
        jbtnl1q2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnl1q2.setText("NEXT");
        jbtnl1q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnl1q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnl1q2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnl1q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 140, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kinergatrhef.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtl1q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtl1q2ActionPerformed
       
    }//GEN-LAST:event_jtxtl1q2ActionPerformed

    private void jbtntryl1q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntryl1q2ActionPerformed
        level11 l1 = new level11();
        l1.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtntryl1q2ActionPerformed

   

    private void jbtnmod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmod1ActionPerformed
        String l1q2;
        l1q2 = jtxtl1q2.getText();
        
        if(l1q2.compareTo("rumah")!=0)
        {
             JOptionPane.showMessageDialog (null, "WRONG ANSWER ! ");
        }
        else if(l1q2.compareTo("rumah")==0)
        {
           JOptionPane.showMessageDialog (null, "CONGRATULATION ! PLEASE CLICK NEXT FOR UPDATE NEXT LEVEL ");
        }
        
    }//GEN-LAST:event_jbtnmod1ActionPerformed

    private void jbtnl1q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnl1q2ActionPerformed
        level2 mzma = new level2();
        mzma.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtnl1q2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnl1q2;
    private javax.swing.JButton jbtnmod1;
    private javax.swing.JButton jbtntryl1q2;
    private javax.swing.JTextField jtxtl1q2;
    // End of variables declaration//GEN-END:variables
}
