
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marina ahmad
 */
public class level33 extends javax.swing.JFrame {

    /**
     * Creates new form level33
     */
    public level33() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtl3q2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtntryl3q2 = new javax.swing.JButton();
        jbtnmod3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("  Soalan 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 50));

        jtxtl3q2.setBackground(new java.awt.Color(153, 204, 255));
        jtxtl3q2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jtxtl3q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jtxtl3q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 184, 57));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("SPELL IT ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 30));

        jbtntryl3q2.setBackground(new java.awt.Color(153, 204, 255));
        jbtntryl3q2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtntryl3q2.setText("TRY AGAIN");
        jbtntryl3q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtntryl3q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntryl3q2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtntryl3q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 160, 50));

        jbtnmod3.setBackground(new java.awt.Color(153, 204, 255));
        jbtnmod3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnmod3.setText("END");
        jbtnmod3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnmod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmod3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 140, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plane.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloud.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnmod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmod3ActionPerformed
         
        String l3q2;
        l3q2 = jtxtl3q2.getText();
        
        if(l3q2.compareTo("aeroplane")!=0)
        {
             JOptionPane.showMessageDialog (null, "WRONG ANSWER !");
        }
        else if(l3q2.compareTo("aeroplane")== 0)
        {
            JOptionPane.showMessageDialog (null, "CONGRATULATION ! YOU HAVE COMPLETE ALL LEVEL !!!!!! ");
        }
        MENU m = new MENU();
        m.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtnmod3ActionPerformed

    
    
    private void jbtntryl3q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntryl3q2ActionPerformed
         level33 kiki = new level33();
        kiki.setVisible(true);
        hide();
        
    }//GEN-LAST:event_jbtntryl3q2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level33().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnmod3;
    private javax.swing.JButton jbtntryl3q2;
    private javax.swing.JTextField jtxtl3q2;
    // End of variables declaration//GEN-END:variables
}
