
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marina ahmad
 */
public class level1 extends javax.swing.JFrame {

    /**
     * Creates new form level1
     */
    public level1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtl1q1 = new javax.swing.JTextField();
        jbtntryl1q1 = new javax.swing.JButton();
        jbtnnextl1q1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image e.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 270, 190));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("    LEVEL 1 \t\t\t\t ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 218, 65));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("You have to answer all the questions correctly! ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 540, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText(" Soalan 1 ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Apakah huruf yang patut diletakkan selepas huruf E? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 440, 87));

        jtxtl1q1.setBackground(new java.awt.Color(255, 204, 204));
        jtxtl1q1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jtxtl1q1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtl1q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtl1q1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtl1q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 130, 110));

        jbtntryl1q1.setBackground(new java.awt.Color(255, 51, 102));
        jbtntryl1q1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtntryl1q1.setText("TRY AGAIN");
        jbtntryl1q1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtntryl1q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntryl1q1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtntryl1q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 240, 50));

        jbtnnextl1q1.setBackground(new java.awt.Color(255, 51, 102));
        jbtnnextl1q1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnnextl1q1.setText("NEXT");
        jbtnnextl1q1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtnnextl1q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnextl1q1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnnextl1q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 230, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kindergarten5.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -140, 1050, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtl1q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtl1q1ActionPerformed
       
    }//GEN-LAST:event_jtxtl1q1ActionPerformed

    private void jbtntryl1q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntryl1q1ActionPerformed
        level1 l = new level1();
        l.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtntryl1q1ActionPerformed

    private void jbtnnextl1q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnextl1q1ActionPerformed
       
        String l1q1;
        l1q1 = jtxtl1q1.getText();
        
        if(l1q1.compareTo("F")!=0)
        {
             JOptionPane.showMessageDialog (null, "WRONG ANSWER !");
        }
        
        
        else 
        {
        
        level11 hi = new level11();
        hi.setVisible(true);
        hide();
        }
    }//GEN-LAST:event_jbtnnextl1q1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnnextl1q1;
    private javax.swing.JButton jbtntryl1q1;
    private javax.swing.JTextField jtxtl1q1;
    // End of variables declaration//GEN-END:variables
}
