/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marina ahmad
 */
public class level extends javax.swing.JFrame {

    /**
     * Creates new form level
     */
    public level() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtneasy = new javax.swing.JButton();
        jbtnmedium = new javax.swing.JButton();
        jbtnhard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("           Test LEVEL");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 420, 80));

        jbtneasy.setBackground(new java.awt.Color(255, 51, 51));
        jbtneasy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtneasy.setText("EASY");
        jbtneasy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtneasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneasyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtneasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 155, 58));

        jbtnmedium.setBackground(new java.awt.Color(255, 51, 51));
        jbtnmedium.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnmedium.setText("MEDIUM");
        jbtnmedium.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtnmedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmediumActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 154, 63));

        jbtnhard.setBackground(new java.awt.Color(255, 51, 51));
        jbtnhard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnhard.setText("HARD");
        jbtnhard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtnhard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhardActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnhard, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 156, 63));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kindergaten 4.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtneasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneasyActionPerformed
        level1 mz= new level1();
        mz.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtneasyActionPerformed

    private void jbtnmediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmediumActionPerformed
         level2 ma = new level2();
        ma.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtnmediumActionPerformed

    private void jbtnhardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhardActionPerformed
         level3 mm = new level3();
        mm.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtnhardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtneasy;
    private javax.swing.JButton jbtnhard;
    private javax.swing.JButton jbtnmedium;
    // End of variables declaration//GEN-END:variables
}
