
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marina ahmad
 */
public class level22 extends javax.swing.JFrame {

    /**
     * Creates new form level22
     */
    public level22() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtl2q2 = new javax.swing.JTextField();
        jbtntryl2q2 = new javax.swing.JButton();
        jbtnmodl2 = new javax.swing.JButton();
        jbtnl2q2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Question 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 103, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokok.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Gambar di bawah menunjukkan sebuah apa? Ejakan _o_ok");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 509, 40));

        jtxtl2q2.setBackground(new java.awt.Color(153, 255, 153));
        jtxtl2q2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jtxtl2q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jtxtl2q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 149, 270, 70));

        jbtntryl2q2.setBackground(new java.awt.Color(204, 204, 0));
        jbtntryl2q2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtntryl2q2.setText("TRY AGAIN");
        jbtntryl2q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtntryl2q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntryl2q2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtntryl2q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 285, 140, 60));

        jbtnmodl2.setBackground(new java.awt.Color(204, 204, 0));
        jbtnmodl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnmodl2.setText("END");
        jbtnmodl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnmodl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodl2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmodl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 285, 120, 60));

        jbtnl2q2.setBackground(new java.awt.Color(153, 153, 0));
        jbtnl2q2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnl2q2.setText("NEXT");
        jbtnl2q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnl2q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnl2q2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnl2q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 285, 130, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/kindergarten7.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnmodl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodl2ActionPerformed

        String l2q2;
        l2q2 = jtxtl2q2.getText();
        
        if(l2q2.compareTo("pokok")!=0)
        {
             JOptionPane.showMessageDialog (null, "WRONG ANSWER !");
        }
        else if( l2q2.compareTo("pokok")== 0)
        {
           JOptionPane.showMessageDialog (null, "CONGRATULATION ! PLEASE CLICK NEXT FOR UPDATE NEXT LEVEL ");
        }
       
    }//GEN-LAST:event_jbtnmodl2ActionPerformed

   
    private void jbtntryl2q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntryl2q2ActionPerformed
         level22 mmm = new level22();
        mmm.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtntryl2q2ActionPerformed

    private void jbtnl2q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnl2q2ActionPerformed
        level3 mmmm= new level3();
        mmmm.setVisible(true);
        hide();
    }//GEN-LAST:event_jbtnl2q2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnl2q2;
    private javax.swing.JButton jbtnmodl2;
    private javax.swing.JButton jbtntryl2q2;
    private javax.swing.JTextField jtxtl2q2;
    // End of variables declaration//GEN-END:variables
}
